"""Make device_id nullable and update device binding logic

Revision ID: 1ce36a970313
Revises: 0ae9e9ccf2fb
Create Date: 2025-03-29 13:30:58.547415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce36a970313'
down_revision = '0ae9e9ccf2fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.String(length=150), nullable=True))
        batch_op.create_unique_constraint(None, ['device_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('device_id')

    # ### end Alembic commands ###
