"""Add credit logs table for transaction tracking

Revision ID: 56caadb8cdf3
Revises: f665c85616cd
Create Date: 2025-06-20 18:58:14.304157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56caadb8cdf3'
down_revision = 'f665c85616cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_constraint('device_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('device_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
