"""added multiple devices to binding

Revision ID: 6aeb6638a4b8
Revises: 1ce36a970313
Create Date: 2025-03-29 18:52:05.034411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aeb6638a4b8'
down_revision = '1ce36a970313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_devices', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('max_devices')

    # ### end Alembic commands ###
