"""Add cascade delete to credit_log and security_audit_log foreign keys

Revision ID: a05f9e721850
Revises: 10876d3130de
Create Date: 2025-06-30 15:19:02.195066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a05f9e721850'
down_revision = '10876d3130de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_log', schema=None) as batch_op:
        batch_op.drop_constraint('credit_log_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('security_audit_log', schema=None) as batch_op:
        batch_op.drop_constraint('security_audit_log_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_audit_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('security_audit_log_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('credit_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('credit_log_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
