"""Add last_credit_consumption column to User model

Revision ID: af7a0bd2a688
Revises: 248e879d6ebe
Create Date: 2025-07-11 14:56:30.692024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af7a0bd2a688'
down_revision = '248e879d6ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_credit_consumption', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_credit_consumption')

    # ### end Alembic commands ###
