"""Add back expiration_date and is_active columns

Revision ID: c9a5f16d691d
Revises: 69a73ab1cfa7
Create Date: 2025-03-28 18:24:46.797533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9a5f16d691d'
down_revision = '69a73ab1cfa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('expiration_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('expiration_date')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
