"""Add role-based hierarchy system with godadmin, admin, reseller, customer roles

Revision ID: ed871eea56da
Revises: 56caadb8cdf3
Create Date: 2025-06-20 20:14:35.113088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed871eea56da'
down_revision = '56caadb8cdf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_log', schema=None) as batch_op:
        batch_op.alter_column('performed_by',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        # Add role column as nullable first
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'user', ['parent_id'], ['id'])
        batch_op.drop_column('credit_type')
        batch_op.drop_column('expiration_date')
        batch_op.drop_column('initial_credits')
        batch_op.drop_column('subscription_type')
        batch_op.drop_column('is_active')

    # Update existing users to have 'customer' role
    op.execute("UPDATE \"user\" SET role = 'customer' WHERE role IS NULL")
    
    # Now make role column not null
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subscription_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('initial_credits', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('expiration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('credit_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('role')

    with op.batch_alter_table('credit_log', schema=None) as batch_op:
        batch_op.alter_column('performed_by',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
