"""Add subscription_type column

Revision ID: 0ae9e9ccf2fb
Revises: c9a5f16d691d
Create Date: 2025-03-29 12:28:05.625808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae9e9ccf2fb'
down_revision = 'c9a5f16d691d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('subscription_type')

    # ### end Alembic commands ###
