"""Add device_credits column to Device model

Revision ID: 10876d3130de
Revises: 34fec1f45219
Create Date: 2025-06-23 20:31:30.913286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10876d3130de'
down_revision = '34fec1f45219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_credits', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('device_credits')

    # ### end Alembic commands ###
