"""remove_device_credits_column

Revision ID: 248e879d6ebe
Revises: a05f9e721850
Create Date: 2025-06-30 17:32:25.135076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248e879d6ebe'
down_revision = 'a05f9e721850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('device_credits')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_credits', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
