"""Re-add initial_credits column

Revision ID: 34fec1f45219
Revises: ed871eea56da
Create Date: 2025-06-23 10:22:17.177382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34fec1f45219'
down_revision = 'ed871eea56da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_log', schema=None) as batch_op:
        batch_op.drop_constraint('credit_log_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_credits', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('initial_credits')

    with op.batch_alter_table('credit_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('credit_log_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
