"""Add credits system columns

Revision ID: 66504d7de4fd
Revises: aa2ee8fcbfa1
Create Date: 2025-06-20 11:03:24.850924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66504d7de4fd'
down_revision = 'aa2ee8fcbfa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('initial_credits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('credits_initialized_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('credits_initialized_at')
        batch_op.drop_column('initial_credits')
        batch_op.drop_column('credits')

    # ### end Alembic commands ###
