"""removed unique constraint from device_id

Revision ID: aa2ee8fcbfa1
Revises: 6aeb6638a4b8
Create Date: 2025-03-29 19:08:52.030664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa2ee8fcbfa1'
down_revision = '6aeb6638a4b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_constraint('device_device_id_key', type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_device_id_key', type_='unique')
        batch_op.drop_column('device_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('user_device_id_key', ['device_id'])

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_unique_constraint('device_device_id_key', ['device_id'])

    # ### end Alembic commands ###
