"""Add credit_type column for test and trial accounts

Revision ID: f665c85616cd
Revises: 66504d7de4fd
Create Date: 2025-06-20 14:06:48.126043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f665c85616cd'
down_revision = '66504d7de4fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('credit_type')

    # ### end Alembic commands ###
